### ISSUE TITLE
[LOC] "```JSX" code block is not ended properly 

### ISSUE THREAD

**Issue by OfficeGlobal** [microsoftgraph/msgraph-training-react-native#1]
"```JSX" code block is not ended properly in an article causing MT engine not to translate text under it properly.
**Repro steps**:
1. Go to [https://github.com/microsoftgraph/msgraph-training-react-native/blob/live/tutorial/02-create-app.md](https://github.com/microsoftgraph/msgraph-training-react-native/blob/live/tutorial/02-create-app.md) and view the file in the "raw" mode
2. Search for "file and replace the entire contents with the following."
3. See the "```JSX" code block which is not properly ended 

**Actual results**:
Code block is not ended properly
**Expected results**:
Code block should be ended properly

**GH article**:
https://github.com/microsoftgraph/msgraph-training-react-native/blob/live/tutorial/02-create-app.md
![image](https://user-images.githubusercontent.com/47977325/66984155-7b9d4b00-f0ba-11e9-9633-53c0d4e9d69d.png)

**Comment by jasonjoh** [comment]
Thanks for the report. You do know we accept pull requests right? :)
