### ISSUE TITLE
Unable to use this React Native library for accessing Azure AD API's 

### ISSUE THREAD

**Issue by kkadapa** [microsoftgraph/msgraph-training-react-native#13]
We have an API App Service in Azure and we created two AD Apps one is for the server-side (API) and another is for the client (Mobile App) side. Also, impersonated the API AD App into the Mobile App.

We were unable to implement React Native AD Authentication using the Client App ID and TENANT ID from this link https://docs.microsoft.com/en-us/graph/tutorials/react-native

Which library should we utilize to accomplish React Native AD Auth users to log in only within our organization using our Tenant ID and access the API Content?

I already tried Azure AD Library https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/2367

**Comment by jasonjoh** [comment]
As far as I know what you want to do should be possible, but this isn't really the place to get support for your scenario. This sample is intended to show how to auth and call Microsoft Graph.

Theoretically you should be able to call your custom API using the same techniques.
