### ISSUE TITLE
Unhandled Promise Rejection when attempting to login with MSA

### ISSUE THREAD

**Issue by vvdodiya** [microsoftgraph/msgraph-training-react-native#16]
Hello, 
I download the demo source code and successfully run the app. But after entering an email screen will disappear. please help me to fix issue.

**Comment by jasonjoh** [comment]
Not enough information to hazard a guess. Can you provide more information?

**Comment by vvdodiya** [comment]
Hello,
I download example source code and run after npm and pod install. Example project run and launch successfully. But when I am trying to sign in the Microsoft sign-in screen disappears after the email entered and on click next. Here i attached the recorded video.

https://user-images.githubusercontent.com/24320461/104874518-24e78680-5979-11eb-9b31-20b23fc451de.mov


https://user-images.githubusercontent.com/24320461/104875446-519c9d80-597b-11eb-869b-8209447bd53f.mov

**Comment by jasonjoh** [comment]
Thank you for reporting. I can reproduce this with a personal outlook.com account. I'll investigate it further.

**Comment by jasonjoh** [comment]
Ok I found a fix. Change this line:

https://github.com/microsoftgraph/msgraph-training-react-native/blob/91e52c3f85ce6ad93a61305a679a43d977e23da4/demo/GraphTutorial/auth/AuthManager.ts#L14

To this:

```
redirectUrl: 'graph-tutorial://react-native-auth/',
```

**VERY IMPORTANT:** Include the trailing slash (`/`) in the redirect or iOS won't return from the auth request.
