### ISSUE TITLE
TypeError: Cannot read property 'getAccessToken' of undefined

### ISSUE THREAD

**Issue by harveyconnor** [microsoftgraph/msgraph-training-react-native#19]
### Where did you get the code?
- [X] Followed the tutorial from [Microsoft Graph tutorials](https://docs.microsoft.com/graph/tutorials)

### Describe the bug
Hi everytime I try to do GraphManager.getUser(), it results in this:
```
TypeError: Cannot read property 'getAccessToken' of undefined
```
I have followed the tutorial and still get that bug.

**Comment by jasonjoh** [comment]
Sorry you're having trouble. Can you tell me your versions of `@microsoft/microsoft-graph-client` and `react-native-app-auth`? Also can you post your GraphManager.ts?
