### ISSUE TITLE
iOS: Login verified but not receiving accessToken

### ISSUE THREAD

**Issue by KushalDesai1** [microsoftgraph/msgraph-training-react-native#21]
Followed all the steps mentioned [here](https://github.com/microsoftgraph/msgraph-training-react-native/issues)

Trying to log the token but not receiving seems like I am not receiving it.

**Comment by jasonjoh** [comment]
What is the error you are receiving?

**Comment by KushalDesai1** [comment]
I am receiving "Error: The operation couldn’t be completed. (org.openid.appauth.general error -3.)"
