### ISSUE TITLE
I can add other ressources in scopes...

### ISSUE THREAD

**Issue by LouisG-Katalyse-IS** [microsoftgraph/msgraph-training-react-native#22]
Hello everyone,
I tried to create an native app with your library but it's impossible to add **'https://analysis.windows.net/powerbi/api/Report.Read.All'**
in the scope, it is'nt take into consideration in the request...

Thanks in advance for your help!

**Comment by jasonjoh** [comment]
I'm not familiar with that scope, but it appears to be related to a Power BI REST API, not Microsoft Graph. That's beyond the scope of this sample unfortunately. 

If you're including a non-Graph scope along with Graph scopes in a single auth/token request, that won't work. Tokens are always scoped to a single API.

If you still need assistance, you should post your question on [Microsoft Q&A](https://docs.microsoft.com/answers/products/).
