### ISSUE TITLE
SignOut is not revoking the tokens and the same logged in user displays forever

### ISSUE THREAD

**Issue by kkadapa** [microsoftgraph/msgraph-training-react-native#23]
### Where did you get the code?

- :white_check_mark:  Followed the tutorial from [Microsoft Graph tutorials](https://docs.microsoft.com/graph/tutorials)

### Describe the bug

We are diligently following [this](https://docs.microsoft.com/en-us/graph/tutorials/react-native) tutorial to accomplish React Native AD Authentication. However, while using [this](https://github.com/microsoftgraph/msgraph-training-react-native/blob/main/demo/GraphTutorial/auth/AuthManager.ts) file we were unable to sign out the user from `signOutAsync` method.  While searching online I tried [this](https://github.com/FormidableLabs/react-native-app-auth#revoke) as shown below but I am getting the following error: `[SyntaxError: JSON Parse error: Unexpected identifier "Invariant"]`

Can someone kindly help?

 ```
import AsyncStorage from '@react-native-community/async-storage';
import { authorize, refresh, AuthConfiguration, revoke } from 'react-native-app-auth';
import { Platform } from 'react-native';
import { AuthConfig } from './AuthConfig';

export class AuthManager {

//Sign out/revoke configuration
 const signoutConfig = {
  issuer: 'https://login.microsoftonline.com/'+AuthConfig.tenantId+'/oauth2/v2.0/authorize',
  clientId: AuthConfig.appId,
  redirectUrl: Platform.OS === 'ios' ? 'urn:ietf:wg:oauth:2.0:oob' : 'ourproject://react-native-auth',
  scopes: AuthConfig.appScopes
};

  static signOutAsync = async () => {
    const userToken = await AsyncStorage.getItem('userToken');
    console.log("*****accessToken**** token is",userToken)
    try {      
      const result = await revoke(signoutConfig, {
        tokenToRevoke: userToken,
        includeBasicAuth: true,
        sendClientId: true,
      });
      console.log("result for signout is",result)

    } catch (error) {
      console.log('signout error: ', JSON.parse(error));
    }

    // Clear storage
    await AsyncStorage.removeItem('userToken');
    await AsyncStorage.removeItem('refreshToken');
    await AsyncStorage.removeItem('expireTime');
    await AsyncStorage.removeItem('userEmail');
  }
}
```

**Comment by jasonjoh** [comment]
Microsoft identity platform does not support revoking access tokens ([source](https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-configurable-token-lifetimes#access-tokens)).

**Comment by kkadapa** [comment]
Thanks for the prompt response @jasonjoh . Please see below config we use to Sign In a user on Mobile App.

```
const config: AuthConfiguration = {
  serviceConfiguration: {
    authorizationEndpoint: 'https://login.microsoftonline.com/'+AuthConfig.tenantId+'/oauth2/v2.0/authorize',
    tokenEndpoint: 'https://login.microsoftonline.com/'+AuthConfig.tenantId+'/oauth2/v2.0/token',
  },
  clientId: AuthConfig.appId,
  redirectUrl: Platform.OS === 'ios' ? 'urn:ietf:wg:oauth:2.0:oob' : 'project://react-native-auth',
  scopes: AuthConfig.appScopes
};
```

We are unable to let a different user Login by Logging out current user 
![image](https://user-images.githubusercontent.com/6679852/125325764-4feed980-e30f-11eb-8939-b39989eef98b.png)

**Comment by jasonjoh** [comment]
Ah ok, I see. It looks like the browser is caching the user. Depending on what you are trying to accomplish, you can address this a couple of different ways.

- If you just want to be able to log in with a different account, then adding a `prompt=select_account` to the login parameters will interrupt single sign-on and prompt the user to pick either the already-signed in account or to use a different one. This is what the tutorial does: https://github.com/microsoftgraph/msgraph-training-react-native/blob/71f6dca58473464dd3f5ded5a91e2e654e4aa9a3/demo/GraphTutorial/auth/AuthManager.ts#L16
- If you want to remove the user's credentials from the browser, you'll need send the user in the browser to the [end_session_endpoint](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-protocols-oidc#send-a-sign-out-request). I don't know if the react-native-app-auth library has a way to do this, you may have to use something else to invoke the browser.

**Comment by kkadapa** [comment]
Thanks so much @jasonjoh  `additionalParameters: { prompt: 'select_account' },` should suffice our requirement of signing out the current user.
