### ISSUE TITLE
is it supported for Expo?

### ISSUE THREAD

**Issue by AnasAlamin** [microsoftgraph/msgraph-training-react-native#27]
does this sample project applicable on expo?
or i should eject my project to be able to use the dependencies?

**Comment by jasonjoh** [comment]
It was not created in Expo, and I'm not familiar enough with Expo as a dev tool to comment on how easy/hard it would be to port it over. If you follow the steps at https://docs.microsoft.com/graph/tutorials/react-native you may be able to recreate the project in Expo from scratch?

There is no reason I know of that the dependencies and code in this sample wouldn't work in Expo.
