### ISSUE TITLE
Links are blocked

### ISSUE THREAD

**Issue by anoopbk1989** [microsoftgraph/msgraph-training-react-native#30]
I am getting **"graph-tutorial" links are blocked** message when the sign-in button is clicked and tries to redirect.  Can you please help me with why I am getting this error and how to resolve this?

**Comment by jasonjoh** [comment]
Sounds like you need to register the redirect URL scheme, which is `graph-tutorial`.

For iOS: https://github.com/FormidableLabs/react-native-app-auth#register-redirect-url-scheme
For Android: https://github.com/FormidableLabs/react-native-app-auth#android-setup

**Comment by anoopbk1989** [comment]
Added intent tag in Android Manifest
