### ISSUE TITLE
There is a typo mistake in (Configure dependencies for Android) section

### ISSUE THREAD

**Issue by anshumanpattnaik** [microsoftgraph/msgraph-training-react-native#7]
Hello,
I found there is a typo mistake in (Configure dependencies for Android) section, while i going through the tutorial i found this problem.

https://docs.microsoft.com/en-us/graph/tutorials/react-native?tutorial-step=1

**MIstake**
`defaultConfig {
    manifestPlaceholders = [
        appAuthRedirectScheme: 'graphtutorial'
    ]
}`

**Correction**
`defaultConfig {
    manifestPlaceholders = [
        appAuthRedirectScheme: 'graph-tutorial'
    ]
}`

Please make the correction as soon as possible.

Thanks

**Comment by jasonjoh** [comment]
Thanks for catching this.
